# NOTE: you have to use single-quoted strings in TOML for regular expressions.
# It's the equivalent of r-strings in Python.  Multiline strings are treated as
# verbose regular expressions by Black.  Use [ ] to denote a significant space
# character.
[project]
name = "ML"
version = "0.1.0"
requires-python = "==3.12.*"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "ruff>=0.12.0",
]

[tool.ruff]
line-length = 160

[tool.ruff.format]
# project directories that do not adhere to black standard yet.
exclude = [
]

[tool.pyright]
pythonVersion = "3.12"
pythonPlatform = "Linux"

reportGeneralTypeIssues = "information"
reportOptionalSubscript = "information"
reportOptionalMemberAccess = "information"
reportOptionalCall = "information"
reportOptionalIterable = "information"
reportOptionalContextManager = "information"
reportOptionalOperand = "information"
reportTypedDictNotRequiredAccess = "information"
reportPrivateImportUsage = "information"
reportUnboundVariable = "information"
reportUnusedCoroutine = "information"
