[project]
name = "agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anthropic>=0.50.0",
    "httpx>=0.28.1",
    "mcp[cli]>=0.9.1",
    "numpy>=1.26.4",
    "python-dotenv>=1.1.0",
]
